export const questions = [
  { ru: "Назови двух моих ближайших друзей.", en: "Name two of my closest friends.", p: 2 },
  { ru: "Моя любимая группа, композитор или инструмент?", en: "What's my favorite band, composer, or instrument?", p: 2 },
  { ru: "Что на мне было надето, когда мы встретились первый раз?", en: "What was I wearing when we first met?", p: 3 },
  { ru: "Назови одно из моих увлечений.", en: "Name one of my hobbies.", p: 2 },
  { ru: "Где я родился?", en: "Where was I born?", p: 1 },
  { ru: "Какие у меня сейчас трудности?", en: "What are my current worries or struggles?", p: 4 },
  { ru: "Подробно опиши, что я делал сегодня или вчера.", en: "Describe in detail what I did today or yesterday.", p: 4 },
  { ru: "Когда у меня день рождения?", en: "When is my birthday?", p: 1 },
  { ru: "Кто мой любимый родственник?", en: "Who is my favorite relative?", p: 2 },
  { ru: "Моя самая большая нереализованная мечта?", en: "What is my biggest unfulfilled dream?", p: 5 },
  { ru: "Мой любимый цветок?", en: "What is my favorite flower?", p: 2 },
  { ru: "Чего я больше всего боюсь?", en: "What am I most afraid of?", p: 3 },
  { ru: "В какое время суток я предпочитаю заниматься любовью?", en: "What time of day do I prefer to make love?", p: 3 },
  { ru: "В какой области я чувствую себя наиболее компетентным?", en: "In what area do I feel most competent?", p: 4 },
  { ru: "Что меня сексуально возбуждает?", en: "What do I find sexually attractive?", p: 3 },
  { ru: "Мое любимое блюдо?", en: "What is my favorite dish?", p: 2 },
  { ru: "Как я предпочитаю проводить вечер?", en: "How do I prefer to spend my evenings?", p: 1 },
  { ru: "Мой любимый цвет?", en: "What is my favorite color?", p: 2 },
  { ru: "Какие личные качества я хочу приобрести?", en: "What personal qualities do I want to develop?", p: 4 },
  { ru: "Какой подарок мне понравился бы больше всего?", en: "What gift would I love most?", p: 2 },
  { ru: "Лучшее событие моего детства?", en: "What was the best event from my childhood?", p: 2 },
  { ru: "Как я предпочитаю проводить отпуск?", en: "How do I prefer to spend vacation?", p: 2 },
  { ru: "Назови один из моих любимых способов утешения.", en: "Name one of my favorite ways to be comforted.", p: 4 },
  { ru: "Кто оказывает мне самую большую поддержку (кроме тебя)?", en: "Who gives me the most support (besides you)?", p: 3 },
  { ru: "Мой любимый вид спорта?", en: "What is my favorite sport?", p: 2 },
  { ru: "Чем я, скорее всего, займусь, если есть свободное время?", en: "What am I most likely to do when I have free time?", p: 2 },
  { ru: "Назови одно из дел, которыми я люблю заниматься по выходным.", en: "Name one thing I love doing on weekends.", p: 2 },
  { ru: "Какие страны мы посетили вместе?", en: "Which countries have we visited together?", p: 3 },
  { ru: "Мой любимый фильм?", en: "What is my favorite movie?", p: 2 },
  { ru: "Какие важные события мне предстоят в жизни? Как я к ним отношусь?", en: "What major events are coming up in my life? How do I feel about them?", p: 4 },
  { ru: "Как я предпочитаю решать проблемы?", en: "How do I prefer to solve problems?", p: 2 },
  { ru: "Мой лучший друг в детстве?", en: "Who was my best friend in childhood?", p: 3 },
  { ru: "Мой любимый журнал или издание?", en: "What is my favorite magazine or publication?", p: 2 },
  { ru: "Назови одного из моих соперников или врагов.", en: "Name one of my rivals or enemies.", p: 3 },
  { ru: "Как я представляю себе идеальную работу?", en: "What does my ideal job look like?", p: 4 },
  { ru: "Какая катастрофа меня больше всего пугает?", en: "What catastrophe do I fear most?", p: 4 },
  { ru: "Кого из родственников я люблю меньше всего?", en: "Which relative do I like least?", p: 3 },
  { ru: "Мой любимый праздник?", en: "What is my favorite holiday?", p: 2 },
  { ru: "Какие книги мне нравятся больше всего?", en: "What types of books do I like most?", p: 3 },
  { ru: "Моя любимая телепередача?", en: "What is my favorite TV show?", p: 2 },
  { ru: "Какую сторону кровати я предпочитаю?", en: "Which side of the bed do I prefer?", p: 2 },
  { ru: "Что меня больше всего расстраивает?", en: "What upsets me the most?", p: 4 },
  { ru: "Назови одну из моих проблем или тревог.", en: "Name one of my current worries or concerns.", p: 4 },
  { ru: "Какие у меня проблемы со здоровьем?", en: "What health concerns do I have?", p: 2 },
  { ru: "Когда мне было больше всего стыдно?", en: "When was I most embarrassed?", p: 3 },
  { ru: "Самое плохое событие в моем детстве?", en: "What was the worst event from my childhood?", p: 3 },
  { ru: "Назови двоих людей, которыми я больше всего восторгаюсь.", en: "Name two people I admire most.", p: 4 },
  { ru: "Как зовут моего начальника?", en: "What is my boss's name?", p: 2 },
  { ru: "Из всех людей, которых мы оба знаем, кто мне нравится меньше всего?", en: "Of all people we both know, who do I like least?", p: 3 },
  { ru: "Назови один из моих любимых десертов.", en: "Name one of my favorite desserts.", p: 2 },
  { ru: "Какая погода мне нравится больше всего?", en: "What kind of weather do I like most?", p: 2 },
  { ru: "Назови один из моих любимых романов.", en: "Name one of my favorite novels.", p: 3 },
  { ru: "Какой у меня любимый ресторан?", en: "What is my favorite restaurant?", p: 1 },
  { ru: "Озвучь два моих желания.", en: "Name two of my wishes.", p: 4 },
  { ru: "Есть ли у меня тайные амбиции? Какие?", en: "Do I have any secret ambitions? What are they?", p: 4 },
  { ru: "Какие блюда я терпеть не могу?", en: "What foods do I dislike?", p: 2 },
  { ru: "Мое любимое животное?", en: "What is my favorite animal?", p: 2 },
  { ru: "Моя любимая песня?", en: "What is my favorite song?", p: 2 },
  { ru: "За какую спортивную команду я болею?", en: "Which sports team do I root for?", p: 2 },
  { ru: "О чём я мечтаю перед сном?", en: "What do I think about before falling asleep?", p: 4 },
  { ru: "Что меня раздражает в других людях?", en: "What annoys me most about other people?", p: 3 },
]

export function pickRandom(n = 20) {
  return [...questions].sort(() => Math.random() - 0.5).slice(0, n)
}
